adminEmail: peter@pydantic.dev

# These values are for development testing using k3s
# See https://github.com/cetra3/kubernetes-activitypub-testing for setup details
image:
  pullPolicy: Always
  repository: registry:5000/
  # -- The tag/version of the docker images to use
  tag: latest
  # @ignored
  workerImage: logfire-python-prod
  # @ignored
  backendImage: logfire-python-prod
  # @ignored
  frontendImage: logfire-frontend-prod
  # @ignored
  schedulerImage: logfire-python-prod
  # @ignored
  fusionfireImage: fusionfire-dev

ingress:
  enabled: true
  tls: true
  apiHostname: logfire-api.k3s.local
  frontendHostname: logfire.k3s.local
  maildevHostname: maildev.k3s.local
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: k3s-ca-issuer


logfire-frontend:
  env: 
    - name: DEX_PUBLIC_URL
      value: https://dex.k3s.local

objectStore:
  uri: file:///storage

dev:
  deployPostgres: true
  hostObjectStore: true
  deployMaildev: true

postgresDsn: postgres://postgres:postgres@logfire-postgres:5432/crud
postgresFFDsn: postgres://postgres:postgres@logfire-postgres:5432/ff
postgresIngestDsn: postgres://postgres:postgres@logfire-postgres:5432/ingest


# -- Specify a priority class name to set [pod priority](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority).
priorityClassName: ""

# -- Pod [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context) for details.
podSecurityContext: {}
  # fsGroup: 2000

# -- Define the [count of deployment revisions](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy) to be kept.
# May be set to 0 in case of GitOps deployment approach.
revisionHistoryLimit: 2

# -- Container [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1) for details.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

dex:
  image:
    repository: registry:5000/dex
    tag: latest
  configSecret:
    create: false
    name: logfire-dex-config
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: k3s-ca-issuer
    hosts:
      - host: dex.k3s.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - dex.k3s.local
        secretName: dex-cert
  config:
    storage:
      type: postgres
      config:
        host: logfire-postgres
        port: 5432
        user: postgres
        database: dex
        password: postgres
        ssl:
          mode: disable
    issuer: https://dex.k3s.local/dex
    staticClients: []
    web:
      http: 0.0.0.0:5556
    grpc:
      addr: 0.0.0.0:5557
    oauth2:
      skipApprovalScreen: true
      passwordConnector: local
    enablePasswordDB: true