{{- $serviceName := "logfire-backend" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
  annotations:
    {{- include "logfire.serviceAnnotations" (dict "Values" .Values "serviceName" $serviceName) | nindent 4 }}
spec:
  selector:
    {{- include "logfire.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
  annotations: 
    {{- include "logfire.secretAnnotations" . | nindent 4 }}
    {{- include "logfire.annotations" (dict "Values" .Values "serviceName" $serviceName) | nindent 4 }}
spec:
  {{- if not (hasKey (index .Values $serviceName | default dict) "autoscaling") }}
  replicas: {{ dig "replicas" "1" (index .Values $serviceName | default dict) }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "logfire.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $serviceName }}
  template:
    metadata:
      annotations:
        {{- if or (not .Values.existingSecret.enabled) (empty .Values.existingSecret.annotations) }}
        checksum/logfire-dex-client-secret: {{ include "utils.secretChecksum" (dict "ctx" . "name" (include "logfire.secretName" (dict "ctx" . "secretName" "logfire-dex-client-secret" )) "key" "logfire-dex-client-secret" )}}
        checksum/logfire-jwt-client-secret: {{ include "utils.secretChecksum" (dict "ctx" . "name" (include "logfire.secretName" (dict "ctx" . "secretName" "logfire-jwt-secret" )) "key" "logfire-jwt-secret" )}}
        checksum/logfire-meta-frontend-token: {{ include "utils.secretChecksum" (dict "ctx" . "name" (include "logfire.secretName" (dict "ctx" . "secretName" "logfire-meta-frontend-token" )) "key" "logfire-meta-frontend-token" )}}
        checksum/logfire-meta-write-token: {{ include "utils.secretChecksum" (dict "ctx" . "name" (include "logfire.secretName" (dict "ctx" . "secretName" "logfire-meta-write-token" )) "key" "logfire-meta-write-token" )}}
        {{- end }}
        {{- if or (not .Values.postgresSecret.enabled) (empty .Values.postgresSecret.annotations) }}
        checksum/logfire-postgres-dsn: {{ include "utils.secretChecksum" (dict "ctx" . "name" (include "logfire.postgresSecretName" .) "key" "postgresDsn" )}}
        {{- end }}
        {{- include "logfire.podAnnotations" (dict "Values" .Values "serviceName" $serviceName) | nindent 8 }}
      labels:
        {{- include "logfire.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $serviceName }}
    spec:
      priorityClassName: {{ .Values.priorityClassName }}
      {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . | quote }}
      {{- end }}
      {{- end }}
      {{- with (index .Values $serviceName | default dict).initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $serviceName }}
          image: '{{ .Values.image.repository | default "" }}{{ .Values.image.backendImage }}:{{ include "logfire.defaultTag" .  }}'
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- include "logfire.resources" (dict "Values" .Values "serviceName" $serviceName) | nindent 10 }}
          command: ["python", "-m", "logfire_backend"]
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          env:
            - name: APP_PORT
              value: "8000"
            - name: CRUD_PG_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "logfire.postgresSecretName" . }}
                  key: postgresDsn
            - name: SHARED_REDIS_DSN
              value: {{ .Values.redisDsn }}
            - name: REDIS_DSN
              value: {{ .Values.redisDsn }}
            - name: WORKER_REDIS_DSN
              value: {{ .Values.redisDsn }}
            - name: USAGE_REDIS_DSN
              value: {{ .Values.redisDsn }}
            - name: DEX_INTERNAL_URL
              value: http://logfire-dex:5556
            {{- with .Values.ai }}
            {{- with .model }}
            - name: AI_MODEL
              value: {{ . }}
            {{- end }}
            {{- with .openAi.apiKey }}
            - name: OPENAI_API_KEY
              value: {{ . }}
            {{- end }}
            {{- with .vertexAi.region }}
            - name: GOOGLE_CLOUD_LOCATION
              value: {{ . }}
            {{- end }}
            {{- with .azureOpenAi }}
            {{- with .endpoint}}
            - name: AZURE_OPENAI_ENDPOINT
              value: {{ . }}
            {{- end }}
            {{- with .apiKey}}
            - name: AZURE_OPENAI_API_KEY
              value: {{ . }}
            {{- end }}
            {{- with .apiVersion}}
            - name: OPENAI_API_VERSION
              value: {{ . }}
            {{- end }}
            {{- end }}
            {{- end }}
            - name: DEX_CLIENT_ID
              value: {{ include "logfire.dexClientId" . }}
            - name: DEX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "logfire.secretName" (dict "ctx" . "secretName" "logfire-dex-client-secret") }}
                  key: logfire-dex-client-secret
            - name: ON_PREM
              value: "true"
            - name: BROWSER_TELEMETRY_COLLECTOR_OTLP_HTTP_HOST
              value: http://logfire-otel-collector:4318
            - name: COLLECTOR_OTLP_GRPC_HOST
              value: http://logfire-otel-collector:4317
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: vcs.repository.url.full=https://github.com/pydantic/platform,vcs.repository.ref.revision={{ .Chart.AppVersion | default "main" | quote }},logfire.code.work_dir=/app
            - name: LOGFIRE_SERVICE_NAME
              value: {{ $serviceName }}
            - name: LOGFIRE_SERVICE_VERSION
              value: {{ .Values.appVersion }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "logfire.secretName" (dict "ctx" . "secretName" "logfire-jwt-secret") }}
                  key: logfire-jwt-secret
            - name: FUSIONFIRE_HOST
              value: http://logfire-ff-query-api
            - name: FUSIONFIRE_PORT
              value: "8011"
            - name: FUSIONFIRE_INGEST_HOST
              value: http://logfire-ff-ingest
            - name: FUSIONFIRE_INGEST_PORT
              value: "8012"
            - name: MIN_DATE_USAGE_CHART  # TODO: make this optional?
              value: "2025-01-01"
            - name: DEFAULT_SUBSCRIPTION_PLAN
              value: non_stripe
            - name: LOGFIRE_REGION
              value: {{ .Values.logfireRegion | default "local" }}
            - name: KNOWN_LOGFIRE_REGIONS
              value: '[{"name": "local", "frontend_host": "{{ include "logfire.url" . }}", "api_host": "{{ include "logfire.url" . }}", "auth_host": "{{ include "logfire.url" . }}"}]'
            - name: FRONTEND_HOST
              value: {{ include "logfire.url" . | quote }}
            - name: META_WRITE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "logfire.secretName" (dict "ctx" . "secretName" "logfire-meta-write-token") }}
                  key: logfire-meta-write-token
            - name: META_FRONTEND_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "logfire.secretName" (dict "ctx" . "secretName" "logfire-meta-frontend-token") }}
                  key: logfire-meta-frontend-token
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "logfire.adminSecretName" (dict "ctx" . "secretName" "logfire-admin-password") }}
                  key: logfire-admin-password
            - name: ADMIN_TOTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "logfire.adminSecretName" (dict "ctx" . "secretName" "logfire-admin-totp-secret") }}
                  key: logfire-admin-totp-secret
            - name: ADMIN_TOTP_RECOVERY_CODES
              valueFrom:
                secretKeyRef:
                  name: {{ include "logfire.adminSecretName" (dict "ctx" . "secretName" "logfire-admin-totp-recovery-codes") }}
                  key: logfire-admin-totp-recovery-codes
            - name: BOOTSTRAPPED_ORGANIZATIONS
              # This will make it possible to log-in sans-credentials by visiting a URL like:
              # http://localhost:8080/logfire-meta/logfire-meta#token=U8TO1taNdD7YwgBMcfeQVU7RB6Hgtrwd
              # You'll need to get the right host and get the secret from k8s
              value: '[{"admin_user_email": "{{ .Values.adminEmail }}", "admin_user_password": "$(ADMIN_PASSWORD)", "admin_user_totp_secret": "$(ADMIN_TOTP_SECRET)", "admin_user_totp_recovery_codes": $(ADMIN_TOTP_RECOVERY_CODES), "organization_name": "logfire-meta", "projects": [{"project_name": "logfire-meta", "write_token": "$(META_WRITE_TOKEN)", "permanent_frontend_token": "$(META_FRONTEND_TOKEN)"}]}]'
            {{- with (index .Values $serviceName | default dict).env }}
              {{- . | toYaml | nindent 12 }}
            {{- end}}
{{- template "logfire.hpa" (dict "Values" .Values "serviceName" $serviceName) }}
{{- template "logfire.pdb" (dict "root" $ "serviceName" $serviceName) }}
