{{- if and .Values.scheduledQueryResults.persistence.enabled (not .Values.scheduledQueryResults.persistence.existingClaim) }}
{{- include "logfire.validateConfig" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "logfire.scheduledQueryResultsClaim" . }}
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    {{- toYaml .Values.scheduledQueryResults.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.scheduledQueryResults.persistence.storage }}
  {{- with .Values.scheduledQueryResults.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
