{{- $serviceName := "logfire-ff-conhash-cache" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conhash
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: conhash-role
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conhash-rolebinding
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: conhash-role
subjects:
  - kind: ServiceAccount
    name: conhash