{{- if .Values.legacyIngest.enabled }}
{{- $serviceName := "logfire-ff-ingest-api" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
  annotations:
    {{- include "logfire.serviceAnnotations" (dict "Values" .Values "serviceName" $serviceName) | nindent 4 }}
spec:
  selector:
    {{- include "logfire.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
  ports:
  - port: 8012
    targetPort: 8012
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
  annotations:
    {{- include "logfire.postgresSecret.annotations" . | nindent 4 }}
    {{- include "logfire.annotations" (dict "Values" .Values "serviceName" $serviceName) | nindent 4 }}
spec:
  {{- if not (hasKey (index .Values $serviceName | default dict) "autoscaling") }}
  replicas: {{ dig "replicas" "1" (index .Values $serviceName | default dict) }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "logfire.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $serviceName }}
  template:
    metadata:
      labels:
        {{- include "logfire.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $serviceName }}
      annotations:
        checksum/ff-config: {{ include (print $.Template.BasePath "/logfire-ff-config.yaml") . | sha256sum }}
        {{- if or (not .Values.postgresSecret.enabled) (empty .Values.postgresSecret.annotations) }}
        checksum/logfire-postgres-ff-dsn: {{ include "utils.secretChecksum" (dict "ctx" . "name" (include "logfire.postgresSecretName" .) "key" "postgresFFDsn" )}}
        checksum/logfire-postgres-ingest-dsn: {{ include "utils.secretChecksum" (dict "ctx" . "name" (include "logfire.postgresSecretName" .) "key" "postgresIngestDsn" )}}
        {{- end }}
        {{- include "logfire.podAnnotations" (dict "Values" .Values "serviceName" $serviceName) | nindent 8 }}
    spec:
      priorityClassName: {{ .Values.priorityClassName }}
      {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . | quote }}
      {{- end }}
      {{- end }}
      {{- with (index .Values $serviceName | default dict).initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $serviceName }}
          image: '{{ .Values.image.repository | default "" }}{{ .Values.image.fusionfireImage }}:{{ include "logfire.defaultTag" .  }}'
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- include "logfire.resources" (dict "Values" .Values "serviceName" $serviceName) | nindent 10 }}
          command:
            - fusionfire
            - ingest
            - --host=0.0.0.0
            - --port=8012
          ports:
            - containerPort: 8012
          envFrom:
            - configMapRef:
                name: logfire-ff-config
          env:
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "0.05"
            - name: OTEL_TRACES_SAMPLER
              value: "parentbased_traceidratio"
            {{- include "logfire.otlpExporterEnv" $serviceName | nindent 12 }}
            - name: FF_WRITE_TOKEN_MEMORY_CACHE_TTL
              value: "500ms"
            - name: FF_TAIL_PATH
              value: "ff"
            - name: FF_UNPACK_SPAN_EVENTS
              value: "true"
            - name: FF_INGEST_MAX_FUTURE_TIME_DRIFT
              value: "3650000d"
            - name: FF_INGEST_MAX_PAST_TIME_DRIFT
              value: "3650000d"
            - name: RUST_BACKTRACE
              value: "1"
            - name: FF_ENABLE_SPILL_TO_DISK
              value: "false"
            - name: PG_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "logfire.postgresSecretName" . }}
                  key: postgresFFDsn
            - name: FF_SHARED_REDIS_DSN
              value: {{ .Values.redisDsn }}
            - name: FF_INGEST_PG_DSN_1
              valueFrom:
                secretKeyRef:
                  name: {{ include "logfire.postgresSecretName" . }}
                  key: postgresIngestDsn
            {{- include "logfire.objectStoreEnv" . | nindent 12 -}}
            {{- with (index .Values $serviceName | default dict).env }}
              {{- . | toYaml | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8012
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8012
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

{{- template "logfire.hpa" (dict "Values" .Values "serviceName" $serviceName) }}
{{- template "logfire.pdb" (dict "root" $ "serviceName" $serviceName) }}
{{- end }}