{{ if (.Values.dev).deployMinio }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logfire-minio
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: logfire-minio
spec:
  serviceName: "logfire-minio"
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "logfire.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: logfire-minio
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "logfire.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: logfire-minio
    spec:
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
          command:
            - minio
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: logfire-minio
            - name: MINIO_ROOT_PASSWORD
              value: logfire-minio
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    # Wait for the server to start
                    sleep 5
                    # Create a bucket
                    mc mb logfire/logfire >> /startup-log.txt 2>&1
                    mc anonymous set public logfire/logfire >> /startup-log.txt 2>&1
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 32Gi
---
apiVersion: v1
kind: Service
metadata:
  name: logfire-minio
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: logfire-minio
spec:
  selector:
    {{- include "logfire.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: logfire-minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
{{ end }}
