{{ if (.Values.dev).deployPostgres }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-scripts
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: logfire-postgres
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "-1"
data:
  create_databases.sql: |
    CREATE DATABASE crud;
    CREATE DATABASE ingest;
    CREATE DATABASE dex;
    CREATE DATABASE ff;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logfire-postgres
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: logfire-postgres
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "-1"
spec:
  serviceName: "logfire-postgres"
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "logfire.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: logfire-postgres
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "logfire.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: logfire-postgres
    spec:
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: postgres
          image: {{ .Values.dev.postgresImage | default "postgres:16" }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          volumeMounts:
            - name: init-db-scripts
              mountPath: /docker-entrypoint-initdb.d
            - name: data
              mountPath: /var/lib/postgresql
              subPath: data
      volumes:
        - name: init-db-scripts
          configMap:
            name: db-init-scripts
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: logfire-postgres
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
    app.kubernetes.io/component: logfire-postgres
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "-1"
spec:
  selector:
    {{- include "logfire.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: logfire-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
{{ end }}
