{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: logfire-api-ingress
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.apiHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: logfire-service
                port:
                  number: 80
  {{- if .Values.ingress.tls }}
  tls:
    - secretName: logfire-api-cert
      hosts:
        - {{ .Values.ingress.apiHostname }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: logfire-frontend-ingress
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.frontendHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: logfire-service
                port:
                  number: 80
  {{- if .Values.ingress.tls }}
  tls:
    - secretName: logfire-frontend-cert
      hosts:
        - {{ .Values.ingress.frontendHostname }}
  {{- end }}
{{- end }}
