adminEmail: hello@example.dev

ingress:
  enabled: true
  tls: false
  hostnames:
  - logfire.example.com
  maildevHostname: maildev.example.com

objectStore:
  uri: s3://logfire
  env:
    AWS_ACCESS_KEY_ID: logfire-minio
    AWS_SECRET_ACCESS_KEY: logfire-minio
    AWS_ENDPOINT: http://logfire-minio:9000
    AWS_ALLOW_HTTP: "true"

dev:
  deployPostgres: true
  deployMinio: true
  deployMaildev: true

postgresSecret:
  enabled: true
  name: "pg-dsns"

existingSecret:
  enabled: true
  name: "logfire-tokens"

adminSecret:
  enabled: true
  name: "logfire-admin"

logfire-dex:
  initContainers:
  - name: check-db-ready
    image: postgres:17
    command: ['sh', '-c', 'until pg_isready -h logfire-postgres -p 5432; do echo "Waiting for postgres..."; sleep 2; done']
  config:
    storage:
      type: postgres
      config:
        host: logfire-postgres
        port: 5432
        user: postgres
        database: dex
        password: postgres
        ssl:
          mode: disable
    staticClients: []

logfire-backend:
  initContainers:
  - name: check-db-ready
    image: postgres:17
    command: ['sh', '-c', 'until pg_isready -h logfire-postgres -p 5432; do echo "Waiting for postgres..."; sleep 2; done']
  pdb:
    minUnavailable: 1

logfire-ff-maintenance-worker:
  scratchVolume:
    storageClassName: standard
    storage: "1Gi"

logfire-ff-ingest:
  volumeClaimTemplates:
    storageClassName: standard
    storage: "1Gi"
  autoscaling:
    hpa:
      enabled: true
      memAverage: 65
      cpuAverage: 20
    minReplicas: 1
    maxReplicas: 2

logfire-ff-compaction-worker:
  scratchVolume:
    storageClassName: standard
    storage: "1Gi"
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    # -- backward compat
    memAverage: 65
    cpuAverage: 20

postgresql:
  primary:
    persistence:
      size: 1Gi

minio:
  persistence:
    enabled: false
